import "./globals.css"

import { ClerkProvider } from "@clerk/nextjs"
import type { Metadata } from "next"
import { Inter } from "next/font/google"

import { Navbar } from "@/_components/index"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Next 15",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className={inter.className}>
					<div className="w-full bg-white px-4 md:px-8 lg:px-16 xl:px-32 2xl:px-64">
						<Navbar />
					</div>
					<div className="w-full bg-slate-100 px-4 md:px-8 lg:px-16 xl:px-32 2xl:px-64">
						{children}
					</div>
				</body>
			</html>
		</ClerkProvider>
	)
}
